HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = 'flask_upshared'
USERNAME = 'root'
PASSWORD = '123456'
MYSQL_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)

SQLALCHEMY_SERVER_TRACK_MODIFICATIONS = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = MYSQL_URI